CycleCountSystem (CSS)/Controllers/AkunController.cs
using CycleCountSystem__CSS_.LoginSecurity;
using CycleCountSystem__CSS_.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
namespace CycleCountSystem__CSS_.Controllers
{
    public class AkunController : Controller
    {
        private CyclecountsystemEntities db = new CyclecountsystemEntities();
        [AuthorizationHandlerAttribute(Roles = "1,2")]

        // GET: Role
        public ActionResult Index()
        {
            var DataAkun = db.TB_Akun.ToList();
            var data = new CombineViewModel
            {
                ListAkun = DataAkun,
                ModelAkun = new Models.TB_Akun()
            };
            return View(data);
        }

        // GET: User/Create
        public ActionResult Create()
        {
            var model = new CombineViewModel();
            model.ModelAkun = new TB_Akun();
            model.ListAkun = db.TB_Akun.ToList();
            return View(model);
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CombineViewModel data)
        {
            if (ModelState.IsValid)
            {
                db.TB_Akun.Add(data.ModelAkun);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            data.ListAkun = db.TB_Akun.ToList();
            return View("Create", data);
        }

        // GET: Inventory/Edit/5
        public ActionResult Edit(int id)
        {
            var dataAkun = db.TB_Akun.FirstOrDefault(x => x.Id_akun == id);
            if (dataAkun != null)
            {
                var akun = new CombineViewModel
                {
                    ModelAkun = dataAkun,
                };
                return View(akun);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Inventory/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CombineViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Temukan data yang akan diedit berdasarkan ID
                    var dataAkun = db.TB_Akun.FirstOrDefault(x => x.Id_akun == id);

                    if (dataAkun != null)
                    {
                        // Update properti entitas TB_Akun dengan nilai yang diberikan dalam model CombineViewModel
                        dataAkun.windows_account = model.ModelAkun.windows_account;
                        dataAkun.Id_role = model.ModelAkun.Id_role;

                        // Set status entitas menjadi Modified agar perubahan dikenali oleh DbContext
                        db.Entry(dataAkun).State = EntityState.Modified;

                        // Simpan perubahan ke database
                        db.SaveChanges();
                    }
                    else
                    {
                        // Handle jika data tidak ditemukan
                        return HttpNotFound();
                    }

                    // Redirect kembali ke tampilan Index setelah berhasil mengedit data
                    return RedirectToAction("Index");
                }
                else
                {
                    // Jika model tidak valid, kembalikan tampilan edit dengan model yang sama
                    return View(model);
                }
            }
            catch (Exception)
            {
                // Handle error jika gagal menyimpan perubahan ke database
                return RedirectToAction("Index");
            }
        }

        // GET: Inventory/Delete/5
        public ActionResult Delete(int id)
        {
            var dataAkun = db.TB_Akun.FirstOrDefault(x => x.Id_akun == id);
            if (dataAkun != null)
            {
                var akun = new CombineViewModel
                {
                    ModelAkun = dataAkun,
                };
                return View(akun);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Inventory/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, CombineViewModel data)
        {
            try
            {
                // Temukan data yang akan dihapus dari database
                var dataAkun = db.TB_Akun.FirstOrDefault(x => x.Id_akun == id);
                if (dataAkun != null)
                    db.TB_Akun.Remove(dataAkun);

                db.SaveChanges();
                return RedirectToAction("Index"); // Redirect kembali ke tampilan Index setelah berhasil menghapus data
            }
            catch (Exception)
            {
                // Handle Error if this failed to deleted
                return RedirectToAction("Index"); // Anda dapat memilih tindakan yang sesuai jika terjadi kesalahan
            }
        }

        public ActionResult UnauthorizedAccess()
        {
            return View();
        }
    }
}

CycleCountSystem (CSS)/Views/Akun/Create.cshtml
@model CycleCountSystem__CSS_.Models.CombineViewModel

@{
    Layout = "";
    ViewBag.Title = "Create";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CCI System - Create Email</title>

    <!-- Custom fonts for this template-->
    <link href="~/Theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Theme/css/sb-admin-2.css" rel="stylesheet" />

    <!-- Custom styles for this page -->
    <link href="~/Theme/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        @Html.Action("Sidebar", "Home")
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <form class="form-inline">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Theme/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Create Account</h1>
                        <label for="excelFileInput" class="d-none d-sm-inline-block btn btn-sm shadow-sm" id="uploadButton">
                            @Html.ActionLink("List Data Account", "Index", null, new { @class = "btn btn-info" })
                        </label>
                    </div>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Create Account</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-horizontal">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ModelAkun.windows_account, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-12">
                                                @Html.EditorFor(model => model.ModelAkun.windows_account, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                                @Html.ValidationMessageFor(model => model.ModelAkun.windows_account, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ModelAkun.Id_role, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-12">
                                                @Html.EditorFor(model => model.ModelAkun.Id_role, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                                @Html.ValidationMessageFor(model => model.ModelAkun.Id_role, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-12 text-right">
                                                <button type="submit" value="Create" class="btn btn-primary">Submit</button> |
                                                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Logistics Department 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top BTop Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Theme/vendor/jquery/jquery.min.js"></script>
    <script src="~/Theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- Core plugin JavaScript-->
    <script src="~/Theme/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Theme/js/sb-admin-2.min.js"></script>

    <!-- date-range-picker -->
    <script src="~/Theme/Plugins/daterangepicker/daterangepicker.js"></script>

    <!-- Page level plugins -->
    <script src="~/Theme/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Theme/js/demo/chart-area-demo.js"></script>
    <script src="~/Theme/js/demo/chart-pie-demo.js"></script>

</body>

</html>

CycleCountSystem (CSS)/Views/Akun/Index.cshtml
@model CycleCountSystem__CSS_.Models.CombineViewModel

@{
    Layout = "";
    ViewBag.Title = "Index";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CCI System - Display Data</title>

    <!-- Custom fonts for this template-->
    <link href="~/Theme/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Theme/css/sb-admin-2.css" rel="stylesheet" />

    <!-- Custom styles for this page -->
    <link href="~/Theme/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        @Html.Action("Sidebar", "Home")
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <form class="form-inline">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Theme/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Display Data Account</h1>
                        <label for="excelFileInput" class="d-none d-sm-inline-block btn btn-sm shadow-sm" id="uploadButton">
                            @Html.ActionLink("Create New Account", "Create", null, new { @class = "btn btn-primary" })
                        </label>
                    </div>


                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">DataTables Display</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead style="background-color: #84B6A7">
                                        <tr style="color:aliceblue">
                                            <th>NO</th>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot style="background-color: #84B6A7">
                                        <tr style="color:aliceblue">
                                            <th>NO</th>
                                            <th>Nama</th>
                                            <th>Email</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @{
                                            int counter = 1; // Inisialisasi counter untuk nomor urutan
                                        }

                                        @for (var item = 0; item < Model.ListAkun.Count; item++)
                                        {
                                            <tr>
                                                <td>@counter</td>
                                                <td>@Model.ListAkun[item].windows_account</td>
                                                <td>@Model.ListAkun[item].Id_role</td>
                                                <td>
                                                    <a href="@Url.Action("Edit","Akun", new { id = Model.ListAkun[item].Id_akun})" class="btn btn-info">
                                                        <i class="fas fa-fw fa-edit"></i>
                                                    </a>
                                                    |
                                                    <a href="@Url.Action("Delete","Akun", new { id = Model.ListAkun[item].Id_akun })" class="btn btn-danger">
                                                        <i class="fas fa-fw fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            counter++;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Logistics Department 2023</span>
                        </div>
                    </div>
                </footer>
                <!-- End of Footer -->
            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="~/Theme/vendor/jquery/jquery.min.js"></script>
        <script src="~/Theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="~/Theme/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="~/Theme/js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="~/Theme/vendor/datatables/jquery.dataTables.min.js"></script>
        <script src="~/Theme/vendor/datatables/dataTables.bootstrap4.min.js"></script>

        <!-- Page level custom scripts -->
        <script src="~/Theme/js/demo/datatables-demo.js"></script>
    </div>
</body>

</html>